<?php
/**
 * kPaste   -   kpaste.ir - kcoder.ir
 * 
 * @link        http://kcoder.ir/kpaste
 * @copyright   (c) 2013, kcoder.ir
 * @license     Proprietary
 * 
 * @filename    userbar.phtml
 * @createdat    Aug 12, 2013 3:05:02 PM
 */

if(!function_exists("isAllowed")) {
    function isAllowed($permission, $acl)
    {
        if (!$acl || !is_array($acl))
            return false;
        if (($key = array_search($permission, $acl)) === FALSE) {
            return false;
        }

        return true;
    }
}
if( $this->userType != 'guest' ):
?>
<div id="userbar">
    <ul>
    <?php
        if( $this->userType == 'paster' ):
        ?>
            <li>
                <a href="<?php echo $this->url('paster', array('lang' => substr($this->layout()->language, 0, 2),'action' => 'newPaste')); ?>" 
                   title="<?php echo $this->translate( 'New Paste' ); ?>">
                    <span class='sprite sprite-light icn-new-paste'>
                        
                    </span>
                </a>
            </li>  

            <li>
                <a href="<?php echo $this->url('paster', array('lang' => substr($this->layout()->language, 0, 2),'action' => 'viewMyPastes')); ?>" 
                   title="<?php echo $this->translate( 'My Pastes' ); ?>">
                    <span class='sprite sprite-light icn-pastes'>
                        
                    </span>
                </a>
            </li>
            
        <?php
        elseif( $this->userType == 'admin' || $this->userType == 'masteradmin' ):
        ?>
            <?php
            if( $this->userType == 'masteradmin' ):
            ?>
                

                <li>
                    <a href="<?php echo $this->url('admin', array('lang' => substr($this->layout()->language, 0, 2),'controller' => 'MasterAdmin', 'action' => 'CreateNewAdmin')); ?>" 
                       title="<?php echo $this->translate( 'Create a New Admin' ); ?>">
                        <span class='sprite sprite-light icn-register'>
                            
                        </span>
                    </a>
                </li> 

                

                <li>
                    <a href="<?php echo $this->url('admin', array('lang' => substr($this->layout()->language, 0, 2),'controller' => 'MasterAdmin', 'action' => 'ViewAdmins')); ?>" 
                       title="<?php echo $this->translate( 'View Admins' ); ?>">
                        <span class='sprite sprite-light icn-users'>
                            
                        </span>
                    </a>
                </li> 

            <?php endif; ?>

            <?php if(isAllowed( 'VIEW_USERS', $this->acl )): ?>
                

            <li>
                <a href="<?php echo $this->url('admin', array('lang' => substr($this->layout()->language, 0, 2),'controller' => 'UserManagement', 'action' => 'ViewUsers')); ?>" 
                   title="<?php echo $this->translate( 'View Users' ); ?>">
                    <span class='sprite sprite-light icn-users'>
                        
                    </span>
                </a>
            </li>  

            <?php endif; ?>

            <?php if(isAllowed( 'VIEW_TRANSACTIONS', $this->acl )): ?>
            

            <li>
                <a href="<?php echo $this->url('admin', array('lang' => substr($this->layout()->language, 0, 2),'controller' => 'SystemLog', 'action' => 'ViewTransactions')); ?>" 
                   title="<?php echo $this->translate( 'Transactions' ); ?>">
                    <span class='sprite sprite-light icn-transactions'>
                        
                    </span>
                </a>
            </li>  

            <?php endif; ?>

            <?php if(isAllowed( 'VIEW_PASTES', $this->acl )): ?>
            

            <li>
                <a href="<?php echo $this->url('admin', array('lang' => substr($this->layout()->language, 0, 2),'controller' => 'SystemLog', 'action' => 'ViewPastes')); ?>" 
                   title="<?php echo $this->translate( 'Pastes' ); ?>">
                    <span class='sprite sprite-light icn-pastes'>
                        
                    </span>
                </a>
            </li>  
            <?php endif; ?>

            <?php if(isAllowed( 'VIEW_REPORTED_PASTES', $this->acl )): ?>
            

            <li>
                <a href="<?php echo $this->url('admin', array('lang' => substr($this->layout()->language, 0, 2),'controller' => 'SystemLog', 'action' => 'ViewReportedPastes')); ?>" 
                   title="<?php echo $this->translate( 'Reported Pastes' ); ?>">
                    <span class='sprite sprite-light icn-reported-pastes'>
                        
                    </span>
                </a>
            </li>  
            <?php endif; ?>

            <?php if(isAllowed( 'VIEW_USERS_AD_CAMPAIGNS', $this->acl )): ?>
            

            <li>
                <a href="<?php echo $this->url('admin', array('lang' => substr($this->layout()->language, 0, 2),'controller' => 'SystemLog', 'action' => 'ViewAdCampaigns')); ?>" 
                   title="<?php echo $this->translate( 'Ad Campaigns' ); ?>">
                    <span class='sprite sprite-light icn-campaigns'>
                        
                    </span>
                </a>
            </li>  
            <?php endif; ?>

            <?php if(isAllowed( 'VIEW_SYSTEM_ACTIVITIES', $this->acl )): ?>
            

            <li>
                <a href="<?php echo $this->url('admin', array('lang' => substr($this->layout()->language, 0, 2),'controller' => 'SystemLog', 'action' => 'ViewSystemActivities')); ?>" 
                   title="<?php echo $this->translate( 'System Activities' ); ?>">
                    <span class='sprite sprite-light icn-activities'>
                        
                    </span>
                </a>
            </li>  
            <?php endif; ?>

            <?php if(isAllowed( 'CHANGE_SYSTEM_SETTINGS', $this->acl )): ?>
            

            <li>
                <a href="<?php echo $this->url('admin', array('lang' => substr($this->layout()->language, 0, 2),'controller' => 'SystemSettings', 'action' => 'index')); ?>" 
                   title="<?php echo $this->translate( 'System Settings' ); ?>">
                    <span class='sprite sprite-light icn-settings'>
                        
                    </span>
                </a>
            </li>

            <?php endif; ?>
            
        <?php
        endif;
        ?>
        <li>
            <a href="<?php echo $this->url('kpastecore', array(
                        'lang'          => substr($this->layout()->language, 0, 2), 
                        'controller'    => 'Home', 
                        'action'        => 'announcements'
                    )); ?>" 
               title="<?php echo $this->translate( 'Announcements' ); ?>">
                <span class='sprite sprite-light icn-news'>
                    
                </span>
            </a>
        </li>  

        

        <li>
            <a href="<?php echo $this->url('user', array('lang' => substr($this->layout()->language, 0, 2),'action' => 'MyAccount')); ?>" 
               title="<?php echo $this->translate( 'My Account' ); ?>">
                <span class='sprite sprite-light icn-account'>
                    
                </span>
            </a>
        </li>

        <li>
            <a href="<?php echo $this->url('user', array('lang' => substr($this->layout()->language, 0, 2),'action' => 'logout')); ?>" 
               title="<?php echo $this->translate( 'Log out' ); ?>">
                <span class='sprite sprite-light icn-logout'>
                    
                </span>
            </a>
        </li>
    </ul>
    
    <div id="userbar-custom-tooltip">
        <img src="/themes/<?php echo $this->settings['theme']; ?>/images/custom-tooltip-top-arrow.png" />
        <p>custom-tool-tip</p>
    </div>
</div>
<?php
endif;
?>