<?php
/**
 * kPaste   -   kpaste.ir - kcoder.ir
 * 
 * @link        http://kcoder.ir/kpaste
 * @copyright   (c) 2013, kcoder.ir
 * @license     Proprietary
 * 
 * @filename    submit-ticket.phtml
 * @createdat   Jul 11, 2013 6:50:05 PM
 */
$this->translate('Advertisement');
if(isset($this->error) && $this->error):
?>
    <div class="error">
        <?php 
        switch($this->result):
            case 'ACCESS_DENIED':
                echo '<p>';
                echo $this->translate('Acess Denied! You have to login before submitting new support ticket.');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
            case 'ATTACHMENT_UPLOAD_FAILED':
                echo '<p>';
                echo $this->translate( 'Uploading attachment file failed!' );
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
            case 'INVALID_DATA_PROVIDED':
                echo '<p>';
                echo $this->translate('Please fill out the form correctly.');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
            case 'ATTACHMENT_SIZE_LIMIT_EXCEEDED':
                $maxSize = $this->attachmentSize / 1024;
                echo '<p>';
                echo sprintf( $this->translate( 'The maximum size for attachments is %s KBs!' ), $maxSize );
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
            case 'INVALID_ATTACHMENT_TYPE':
                echo '<p>';
                echo $this->translate('The attachment type is invalid!');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
            case 'RECIPIENT_NOT_SPECIFIED':
                echo '<p>';
                echo $this->translate('The recipient is not specified!');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
            default:
                echo '<p>';
                echo $this->translate('An unknown error has occured!');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
        endswitch; 

        ?>
    </div>
<?php
elseif ( isset($this->error) && !$this->error ):
?>
    <div class="notification">
        <?php if($this->result == 'TICKET_SUBMITTED'): ?>
        <p>
            <?php echo $this->translate( 'The ticket was successfully submitted!' ); ?>
            <a href="<?php echo $this->url('support', array(
                'lang'      => substr($this->layout()->language, 0, 2),
                'action'    => 'ViewTickets',
            )); ?>"><?php echo $this->translate( 'Continue' ); ?></a>
        </p>
        <?php elseif($this->result == 'SUPPORT_EMAIL_SENT'): ?>
        <p>
            <?php echo $this->translate( 'The support message was successfully sent. ' .
                    'We will contact you via email soon.'); ?>
        </p>
        <?php endif; ?>
    </div>
<?php
endif;

if(isset($this->form)):
?>
<h3><?php echo $this->translate('Submit New Ticket'); ?></h3>
<?php


//translate departments
$this->translate('Advertisment');
$this->translate('Pastes');
$this->translate('General Support');
$this->translate('Bug Report');

 
    if( $this->recipient )
        $this->form->setAttribute('action',$this->url('support', array(
            'lang'      => substr($this->layout()->language, 0, 2),
            'action'    => 'SubmitTicket',
            'param1'    => $this->recipient->userid,
        )));
    else
        $this->form->setAttribute('action',$this->url('support', array(
            'lang'      => substr($this->layout()->language, 0, 2),
            'action'    => 'SubmitTicket',
        )));
    $this->form->prepare();
    echo $this->form()->openTag($this->form);
?>
    <div class='width70'>
        <div class="formRow">
            <label>
                <span><?php echo $this->translate('Title'); ?>:</span>
                <?php echo $this->formRow($this->form->get('title')); ?>
            </label>
        </div>

        <div class="formRow">
            <label>
                <span><?php echo $this->translate('Importance'); ?>:</span>
                <?php 
                $this->form->get( 'importance' )->setValueOptions(array(
                    'low'       => $this->translate( 'Low' ),
                    'medium'    => $this->translate( 'Medium' ),
                    'high'      => $this->translate( 'High' ),
                ));
                echo $this->formRow($this->form->get('importance')); 

                ?>
            </label>
        </div>
        <?php if( $this->departments ): ?>
        <div class="formRow">
            <label>
                <span><?php echo $this->translate('Department'); ?>:</span>
                <?php 
                $this->form->get( 'departmentid' )->setValueOptions( $this->departments );
                echo $this->formRow($this->form->get('departmentid')); 
                ?>
            </label>
        </div>
        <?php endif; ?>
        <?php 
        $this->form->get('message')->setAttribute('placeholder', $this->translate('Input your message here...')); 
        echo $this->formRow($this->form->get('message')); 
        ?>
        <br />
        <div class="formRow">
            <label>
                <span><?php echo $this->translate('Attachment'); ?>:</span>
                <?php echo $this->formRow($this->form->get('attachment')); ?>
            </label>
        </div>
        <label class="hint">
            <?php echo $this->translate('Allowed File Types:'); ?>
            <div class="ltr inline-block">
                *.jpg, *.png, *.gif, *.zip
            </div>
        </label>
        <br /><br />
        <div class="captcha">
            <label>
                <span><?php echo $this->translate('Captcha'); ?>:</span><br />
                <?php echo $this->formRow($this->form->get('captcha')); ?>
            </label>
        </div>
        <?php echo $this->formRow( $this->form->get( 'csrf' ) ); ?>
        <button type="submit"><?php echo $this->translate('Submit'); ?></button>
    </div>
<?php
    echo $this->form()->closeTag();
elseif(isset($this->guestForm)):
    $url = $this->url('support', array(
            'lang'      => substr($this->layout()->language, 0, 2),
            'action'    => 'SubmitTicket',
        ));
    $this->guestForm->setAttribute('action',$url);
    $this->guestForm->prepare();
    echo $this->form()->openTag($this->guestForm);
?>
    <h3 class="center-align"><?php echo $this->translate('Contact kPaste\'s Support'); ?></h3>
    <p>
        <?php echo $this->translate('Please note that by signing up and sending a support ticket ' . 
                'we will process your request sooner and better.'); ?>
    </p>
    <div class='width70'>
        <div class="formRow">
            <label>
                <span><?php echo $this->translate('Title'); ?>:</span>
                <?php echo $this->formRow($this->guestForm->get('title')); ?>
            </label>
        </div>
        <div class="formRow">
            <label>
                <span><?php echo $this->translate('Email'); ?>:</span>
                <?php echo $this->formRow($this->guestForm->get('email')); ?>
            </label>
        </div>
        <?php 
        $this->guestForm->get('message')->setAttribute('placeholder', $this->translate('Input your message here...')); 
        echo $this->formRow($this->guestForm->get('message')); 
        ?>
        <br /><br />
        <div class="captcha">
            <label>
                <span><?php echo $this->translate('Captcha'); ?>:</span><br />
                <?php echo $this->formRow($this->guestForm->get('captcha')); ?>
            </label>
        </div>
        <?php echo $this->formRow( $this->guestForm->get( 'csrf' ) ); ?>
        <button type="submit"><?php echo $this->translate('Submit'); ?></button>
    </div>
<?php
    echo $this->form()->closeTag();
endif;
