<?php
if(isset($this->error) && $this->error):
?>
    <div class="error">
        <?php 
        switch($this->result):
            case 'INVALID_EMAIL_PROVIDED':
                echo '<p>';
                echo $this->translate('The provided email does not exist in our database. Please check your information and try again.');
                echo '<br />';
                echo '<a href="'.$this->url('user', array('lang' => substr($this->layout()->language, 0, 2),'action' => 'changePassword')) 
                        .'">' .  $this->translate('Try Again') . '</a><br />';
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
            case 'TOO_MANY_PASSWORD_CHANGE_REQUESTS':
                $tryIn = intval(((time() - strtotime($this->last_request)) / (60 * 60)));
                $tryIn = 24 - $tryIn;
                echo '<p>';
                echo sprintf($this->translate('You can only request a password change once every 24 hours. Try again in %s hours.'), $tryIn);
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
            case 'INVALID_DATA_PROVIDED':
                echo '<p>';
                echo $this->translate('Please fill out the form correctly.');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
            case 'PASSWORD_CHANGE_REQUEST_HAS_EXPIRED':
                echo '<p>';
                echo $this->translate('Password change request has expired. You have 2 hours to complete a password change request from the moment it gets registered.');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
            case 'INVALID_PASSWORD_CHANGE_CONFIRMATION_CODE':
                echo '<p>';
                echo $this->translate('The password change request confirmation code you have provided is incorrect.');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
            case 'PASSWORDS_DO_NOT_MATCH':
                echo '<p>';
                echo $this->translate('The new passwords you have entered do not match!');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
            case 'CURRENT_PASSWORD_IS_WRONG':
                echo '<p>';
                echo $this->translate('The current password is wrong!');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
        endswitch; 

        ?>
    </div>
<?php
elseif ( isset($this->error) && !$this->error ):
?>
    <div class="notification">
        <p>
            <?php 
            switch ($this->result):
                case 'PASSWORD_CHANGED_SUCCESSFULLY':
                    if(isset($this->newPassword))
                        echo sprintf($this->translate('Your password has been changed. Your new password is <span class="new-password">%s</span> Please change your password immediately using the following form.'), $this->newPassword);
                    else
                        echo $this->translate('Your password has been changed. Please login again.');
                    break;
                case 'PASSWORD_CHANGE_REQUEST_SUCCESSFULLY_REGISTERED':
                    echo $this->translate('Your password change request has been successfully registered. <span class="bold">Please be wary that this request will expire in 2 hours.</span>');
                    break;
                default:
                    echo $this->result;
            endswitch;
            ?><br />
        </p>
    </div>
<?php
endif;

if(isset($this->phase1form)) :
?>
<div class='width700p'>
    <h3><?php echo $this->translate('Password Change Request'); ?></h3>
    <p><?php echo $this->translate('Enter your email address and instructions on how to reset your password will be sent to you.'); ?></p>
    <?php
        $this->phase1form->setAttribute('action',$this->url('user', array('lang' => substr($this->layout()->language, 0, 2),'action' => 'changePassword')));
        $this->phase1form->prepare();
        echo $this->form()->openTag($this->phase1form);
    ?>
    
        <div class="formRow">
            <label>
                <span><?php echo $this->translate('Email'); ?>:</span>
                <?php echo $this->formRow($this->phase1form->get('email')); ?>
            </label>
        </div>

        <div class="captcha">
            <label>
                <span><?php echo $this->translate('Captcha'); ?>:</span><br />
                <?php echo $this->formRow($this->phase1form->get('captcha')); ?>
            </label>
        </div>
        <br />
        
        <?php 
        $this->phase1form->get('submit')->setAttribute('value', $this->translate('Request password change'));
        echo $this->formRow($this->phase1form->get('submit')); 
        ?>
    </div>

<?php
    echo $this->form()->closeTag();
elseif(isset($this->phase2form)):
    $this->phase2form->setAttribute('action',
        $this->url('user', array(
                            'lang'                      => substr($this->layout()->language, 0, 2),
                            'action'                    => 'changePassword',
                            'request_confirmation_code' => $this->confirmation,
    )));
    echo $this->form()->openTag($this->phase2form);
?>
    <h3><?php echo $this->translate('Please answer your security question to complete the process:'); ?></h3>

    <div class='width70'>
        <div class="formRow">
            <label>
                <span><?php echo $this->translate('Security Question'); ?>:</span>
                <input type='text' value='<?php echo $this->question; ?>' readonly='readonly' />
            </label>
        </div>

        <div class="formRow">
            <label>
                <span><?php echo $this->translate('Security Question Answer'); ?>:</span>
                <?php echo $this->formRow($this->phase2form->get('security_question_answer')); ?>
            </label>
        </div>

        <div class="captcha">
            <label>
                <span><?php echo $this->translate('Captcha'); ?>:</span><br />
                <?php echo $this->formRow($this->phase2form->get('captcha')); ?>
            </label>
        </div>

        <?php 
        $this->phase2form->get('submit')->setAttribute('value', $this->translate('Change Password'));
        echo $this->formRow($this->phase2form->get('submit')); 
        ?>
    </div>
<?php
    echo $this->form()->closeTag();    
elseif(isset($this->form)):
    $this->form->setAttribute('action',$this->url('user', array('lang' => substr($this->layout()->language, 0, 2),'action' => 'changePassword')));
    echo $this->form()->openTag($this->form);
?>
    <div class='width70'>
        <div class="formRow">
            <label>
                <span><?php echo $this->translate('Current Password'); ?>:</span>
                <?php echo $this->formRow($this->form->get('current_password')); ?>
            </label>
        </div>

        <div class="formRow">
            <label>
                <span><?php echo $this->translate('New Password'); ?>:</span>
                <?php echo $this->formRow($this->form->get('new_password')); ?>
            </label>
        </div>

        <div class="formRow">
            <label>
                <span><?php echo $this->translate('Repeat New Password'); ?>:</span>
                <?php echo $this->formRow($this->form->get('new_password_repeat')); ?>
            </label>
        </div>

        <div class="captcha">
            <label>
                <span><?php echo $this->translate('Captcha'); ?>:</span><br />
                <?php echo $this->formRow($this->form->get('captcha')); ?>
            </label>
        </div>


        <?php 
        $this->form->get('submit')->setAttribute('value', $this->translate('Change Password'));
        echo $this->formRow($this->form->get('submit')); 
        ?>

    </div>
<?php
endif;
