<html>
    <head>
        <title>%TITLE%</title>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
		<style>
                    body {
                        background: #eee; 
                        font-family: Tahoma; 
                        text-align: %TEXTALIGN%; 
                        direction: %DIRECTION%;
                    }
                    h1 {
                        background: #fff; 
                        border: 1px solid #ccc; 
                        border-radius: 10px; 
                        font-size: 24px; 
                        text-align: center;
                        margin: 50px auto 20px; 
                        padding: 10px; 
                        max-width: 800px;
                    }
                    p {
                        background: #fff; 
                        border: 1px solid #ccc; 
                        border-radius: 10px; 
                        margin: 0 auto; 
                        padding: 10px; 
                        max-width: 800px;
                    }
                    a.button {
                        background: #0fa1d7;
                        border: solid 1px #0a8aba;
                        border-radius: 4px;
                        color: #fff;
                        display: inline-block;
                        margin: 10px;
                        padding: 7px 14px;
                        text-decoration: none;
                    }
                    a.button:hover {
                        background: #0daee9;
                    }
		</style>
    </head>
    <body dir="%DIRECTION%">
	<h1>%TITLE%</h1>
        <p>
            %MESSAGE%
        </p>
    </body>
</html>
