<?php
/**
 * kPaste   -   kpaste.ir - kcoder.ir
 * 
 * @link        http://kcoder.ir/kpaste
 * @copyright   (c) 2013, kcoder.ir
 * @license     Proprietary
 * 
 * @filename    delete-paste.phtml
 * @createdat   Jul 15, 2013 4:41:57 PM
 */


$title = $this->translate('Confirm Paste Deletion');
$this->headTitle($title);

if(isset($this->error) && $this->error):
?>
    <div class="error">
        <?php 
        switch($this->result):
            case 'ACCESS_DENIED':
                echo '<p>';
                echo $this->translate('Access denied! You don\'t have permission to access this area.');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
            default:
                echo '<p>';
                echo $this->translate('An unknown error has occured!');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
        endswitch;
        ?>
    </div>
<?php
endif;

if(isset($this->pasteTitle) && isset($this->pasteId)):
?>
    <h2><?php echo sprintf($this->translate('Are you sure you want to delete "%s"?'), $this->pasteTitle); ?></h2>
    <form action='<?php echo $this->url('paster' , array('lang' => substr($this->layout()->language, 0, 2),'action' => 'deletePaste', 'param1' => $this->pasteId)); ?>' method='post' style='display: inline;'>
        <button type="submit" name="confirm" value="NO"><?php echo $this->translate('No'); ?></button>
    </form>
    <form action='<?php echo $this->url('paster' , array('lang' => substr($this->layout()->language, 0, 2),'action' => 'deletePaste', 'param1' => $this->pasteId)); ?>' method='post' style='display: inline;'>
        <button type="submit" name="confirm" value="YES"><?php echo $this->translate('Yes'); ?></button>
    </form>
<?php
endif;