<?php
/**
 * kPaste   -   kpaste.ir - kcoder.ir
 * 
 * @link        http://kcoder.ir/kpaste
 * @copyright   (c) 2013, kcoder.ir
 * @license     Proprietary
 * 
 * @filename    contact-us.phtml
 * @createdat   Oct 25, 2013 3:05:02 PM
 */

$title = $this->translate( 'Contact Us' );
$this->headTitle( $title );
?>

<h4 class="center-align">
    <?php echo $this->translate('Contact Info'); ?>
</h4>
<table class="table" style="width: auto; margin: 0 auto;">
    <tr>
        <td><?php echo $this->translate('Email'); ?></td>
        <td>
            support [at] kpaste.ir
        </td>
    </tr>
</table>
</p>
