<?php
/**
 * kPaste   -   kpaste.ir - kcoder.ir
 * 
 * @link        http://kcoder.ir/kpaste
 * @copyright   (c) 2013, kcoder.ir
 * @license     Proprietary
 * 
 * @filename    qaa.phtml
 * @createdat   Sep 3, 2013 3:05:02 PM
 */

$title = $this->translate( 'Questions & Answers' );
$this->headTitle( $title );
?>
<div class="privacy width700p">
    <p>
        <?php echo $this->qaa; ?>
    </p>
</div>