<?php
/**
 * kPaste   -   kpaste.ir - kcoder.ir
 * 
 * @link        http://kcoder.ir/kpaste
 * @copyright   (c) 2013, kcoder.ir
 * @license     Proprietary
 * 
 * @filename    index.phtml
 * @createdat   sep 2, 2013 4:41:57 PM
 */


$title = $this->translate('System Settings');
$this->headTitle($title);
$url = $this->url( 'admin', array(
        'lang'          => substr($this->layout()->language, 0, 2),
        'controller'    => 'SystemSettings',
        'action'        => 'index',
    ));
if(isset($this->error) && $this->error ):
?>
    <div class="error">
        <?php 
        switch($this->result):
            case 'ACCESS_DENIED':
                echo '<p>';
                echo $this->translate('Access denied! You don\'t have permission to access this area.');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
            default:
                echo '<p>';
                echo $this->translate('An unknown error has occured!');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
        endswitch;
        ?>
    </div>
<?php
endif;

if( isset($this->error) && !$this->error ):
    $lang = substr($this->layout()->language, 0, 2);
?>
<div class="user-panel-items-wrapper">
    <div class="user-panel-items">
        <div class="user-panel-item-image">
            <img src="/themes/<?php echo $this->theme; ?>/images/admin.png" 
                 alt="<?php echo $this->translate('Admins List'); ?>" width="128" height="128" />
        </div>
        <div class="user-panel-item-text">
            <a href="<?php echo $this->url('admin', array(
                'lang'      => $lang,
                'controller'=> 'MasterAdmin',
                'action'    => 'ViewAdmins',
            )); ?>">
                <?php echo $this->translate('Admins List'); ?>
            </a>
        </div>
    </div>
    
    <div class="user-panel-items">
        <div class="user-panel-item-image">
            <img src="/themes/<?php echo $this->theme; ?>/images/newadmin.png" 
                 alt="<?php echo $this->translate('Create New Admin'); ?>" width="128" height="128" />
        </div>
        <div class="user-panel-item-text">
            <a href="<?php echo $this->url('admin', array(
                'lang'      => $lang,
                'controller'=> 'MasterAdmin',
                'action'    => 'ViewAdmins',
            )); ?>">
                <?php echo $this->translate('Create New Admin'); ?>
            </a>
        </div>
    </div>
    
    <div class="user-panel-items">
        <div class="user-panel-item-image">
            <img src="/themes/<?php echo $this->theme; ?>/images/users.png" 
                 alt="<?php echo $this->translate('View Users'); ?>" width="128" height="128" />
        </div>
        <div class="user-panel-item-text">
            <a href="<?php echo $this->url('admin', array(
                'lang'      => $lang,
                'controller'=> 'UserManagement',
                'action'    => 'ViewUsers',
            )); ?>">
                <?php echo $this->translate('View Users'); ?>
            </a>
        </div>
    </div>
    
    <div class="user-panel-items">
        <div class="user-panel-item-image">
            <img src="/themes/<?php echo $this->theme; ?>/images/paste.png" 
                 alt="<?php echo $this->translate('Pastes'); ?>" width="128" height="128" />
        </div>
        <div class="user-panel-item-text">
            <a href="<?php echo $this->url('admin', array(
                'lang'      => $lang,
                'controller'=> 'SystemLog',
                'action'    => 'ViewPastes',
            )); ?>">
                <?php echo $this->translate('Pastes'); ?>
            </a>
        </div>
    </div>
    
    <div class="user-panel-items">
        <div class="user-panel-item-image">
            <img src="/themes/<?php echo $this->theme; ?>/images/abuse.png" 
                 alt="<?php echo $this->translate('Reported Pastes'); ?>" width="128" height="128" />
        </div>
        <div class="user-panel-item-text">
            <a href="<?php echo $this->url('admin', array(
                'lang'      => $lang,
                'controller'=> 'SystemLog',
                'action'    => 'ViewReportedPastes',
            )); ?>">
                <?php echo $this->translate('Reported Pastes'); ?>
            </a>
        </div>
    </div>

    
    <div class="user-panel-items">
        <div class="user-panel-item-image">
            <img src="/themes/<?php echo $this->theme; ?>/images/activity.png" 
                 alt="<?php echo $this->translate('System Activities'); ?>" width="128" height="128" />
        </div>
        <div class="user-panel-item-text">
            <a href="<?php echo $this->url('admin', array(
                'lang'      => $lang,
                'controller'=> 'SystemLog',
                'action'    => 'ViewSystemActivities',
            )); ?>">
                <?php echo $this->translate('System Activities'); ?>
            </a>
        </div>
    </div>
    
    <div class="user-panel-items">
        <div class="user-panel-item-image">
            <img src="/themes/<?php echo $this->theme; ?>/images/general-settings.png" 
                 alt="<?php echo $this->translate('General Settings'); ?>" width="128" height="128" />
        </div>
        <div class="user-panel-item-text">
            <a href="<?php echo $this->url('admin', array(
                'controller'=> 'SystemSettings',
                'lang'      => $lang,
                'action'    => 'GeneralSettings',
            )); ?>">
                <?php echo $this->translate('General Settings'); ?>
            </a>
        </div>
    </div>
    
    <div class="user-panel-items">
        <div class="user-panel-item-image">
            <img src="/themes/<?php echo $this->theme; ?>/images/terms.png" 
                 alt="<?php echo $this->translate('Terms and Privacy Policy'); ?>" width="128" height="128" />
        </div>
        <div class="user-panel-item-text">
            <a href="<?php echo $this->url('admin', array(
                'controller'=> 'SystemSettings',
                'lang'      => $lang,
                'action'    => 'ChangeTermsAndPrivacy',
            )); ?>">
                <?php echo $this->translate('Terms and Privacy Policy'); ?>
            </a>
        </div>
    </div>
    
    <!-- ################################### -->

    <div class="user-panel-items">
        <div class="user-panel-item-image">
            <img src="/themes/<?php echo $this->theme; ?>/images/announcements.png" 
                 alt="<?php echo $this->translate('Announcements'); ?>" width="128" height="128" />
        </div>
        <div class="user-panel-item-text">
            <a href="<?php echo $this->url('kpastecore', array(
                'lang'      => $lang,
                'controller'=> 'Home',
                'action'    => 'Announcements',
            )); ?>">
                <?php echo $this->translate('Announcements'); ?>
            </a>
        </div>
    </div>
    
    <div class="user-panel-items">
        <div class="user-panel-item-image">
            <img src="/themes/<?php echo $this->theme; ?>/images/account.png" 
                 alt="<?php echo $this->translate('My Account'); ?>" width="128" height="128" />
        </div>
        <div class="user-panel-item-text">
            <a href="<?php echo $this->url('user', array(
                'lang'      => $lang,
                'action'    => 'myAccount',
            )); ?>">
                <?php echo $this->translate('My Account'); ?>
            </a>
        </div>
    </div>
    
    <div class="user-panel-items">
        <div class="user-panel-item-image">
            <img src="/themes/<?php echo $this->theme; ?>/images/logout.png" 
                 alt="<?php echo $this->translate('Logout'); ?>" width="128" height="128" />
        </div>
        <div class="user-panel-item-text">
            <a href="<?php echo $this->url('user', array(
                'lang'      => $lang,
                'action'    => 'logout',
            )); ?>">
                <?php echo $this->translate('Logout'); ?>
            </a>
        </div>
    </div>
</div>
<?php
endif;