<?php
/**
 * kPaste   -   kpaste.ir - kcoder.ir
 * 
 * @link        http://kcoder.ir/kpaste
 * @copyright   (c) 2013, kcoder.ir
 * @license     Proprietary
 * 
 * @filename    publish-news.phtml
 * @createdat   aug 5, 2013 4:41:57 PM
 */


$title = $this->translate('Publish News');
$this->headTitle($title);

if(isset($this->error) && $this->error ):
?>
    <div class="error">
        <?php 
        switch($this->result):
            case 'ACCESS_DENIED':
                echo '<p>';
                echo $this->translate('Access denied! You don\'t have permission to access this area.');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
            case 'INVALID_DATA_PROVIDED':
                echo '<p>';
                echo $this->translate('The provided data is invalid!');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
            default:
                echo '<p>';
                echo $this->translate('An unknown error has occured!');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
        endswitch;
        ?>
    </div>
<?php
endif;

if( isset($this->error) && !$this->error ):
?>
<div class='notification'>
    <p>
        <?php echo $this->translate( 'News published successfully!' ); ?>. 
        <a href="<?php echo $this->url( 'kpastecore', array(
            'lang'          => substr($this->layout()->language, 0, 2),
            'controller'    => 'Home',
            'action'        => 'Announcements',
        )); ?>"><?php echo $this->translate( 'View News' ); ?></a>
    </p>
</div>
<?php
endif;

if( isset( $this->form ) ):
?>
<div class="width70">
<?php
    $form = $this->form;
    if( $this->newsid )
        $form->setAttribute( 'action', $this->url( 'admin', array(
            'lang'          => substr($this->layout()->language, 0, 2),
            'controller'    => 'SystemSettings',
            'action'        => 'PublishAnnouncement',
            'param1'        => $this->newsid,
        )));
    else
        $form->setAttribute( 'action', $this->url( 'admin', array(
            'lang'          => substr($this->layout()->language, 0, 2),
            'controller'    => 'SystemSettings',
            'action'        => 'PublishAnnouncement',
        )));
    $form->prepare();
    
    echo $this->form()->openTag( $form );
?>
    <div class="formRow">
        <label>
            <span><?php echo $this->translate( 'Title' ); ?></span>
            <?php echo $this->formRow( $form->get( 'title' ) ); ?>
        </label>
    </div>
    <?php 
    $form->get('news')->setAttribute('placeholder', $this->translate('Announcement'));
    echo $this->formRow( $form->get( 'news' ) ); 
    ?>
    <button type='submit'>
        <?php echo $this->translate( 'Publish Announcement' ); ?>
    </button>
    <?php
        echo $this->form()->closeTag();
?>
</div>
<?php
endif;