<?php
/**
 * kPaste   -   kpaste.ir - kcoder.ir
 * 
 * @link        http://kcoder.ir/kpaste
 * @copyright   (c) 2013, kcoder.ir
 * @license     Proprietary
 * 
 * @filename    account-balance.phtml
 * @createdat   Sep 07, 2013 4:41:57 PM
 */


$title = $this->translate('Account Balance');
$this->headTitle($title);
$url = $this->url( 'advertiser', array(
                'lang'      => substr($this->layout()->language, 0, 2),
                'action'    => 'AccountBalance',
            ) );
$action = $this->url( 'kpastecore', array(
                'lang'      => substr($this->layout()->language, 0, 2),
                'controller'=> 'EPayment',
                'action'    => 'index',
            ) );
if(isset($this->error) && $this->error):
?>
    <div class="error">
        <?php 
        switch($this->result):
            case 'ACCESS_DENIED':
                echo '<p>';
                echo $this->translate('Access denied! You don\'t have permission to access this area.');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
            case 'ACCOUNT_NOT_VERIFIED':
                echo '<p>';
                echo $this->translate('Access denied! Your account is not verified.');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
            default:
                echo '<p>';
                echo $this->translate('An unknown error has occured!');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
        endswitch;
        ?>
    </div>
<?php
else:
?>
<h3 class='center-align'><?php echo $this->translate('Account Balance'); ?> (<?php echo $this->currency; ?>)</h3>
<div class='center-align'><script>createFlipBoard('<?php echo (int)$this->balance; ?>', 'big');</script></div>
<br /><br />

<form action="<?php echo $action; ?>" method="post">
    <h4 class="center-align">
        <?php echo $this->translate('Enter amount to recharge account'); ?>
    </h4>
    <div class="center-align">
        <div class="rechargeFormWrapper">
            <label class="labeledInput">
                <input type="text" name="amount" id="amount" value="100000" maxlength="8" />
                <div></div>
                <?php echo $this->currency; ?>
            </label>
            <br />
            <br />
            <h4 class="center-align"><?php echo $this->translate('Choose Your Gateway'); ?></h4>
            <br />
            
            <div class="inline-block center-align">
                <label>
                    <img src="/images/gateways/melat.png" alt="بانک ملت" />
                    <br />
                    <input type="radio" name="payment_gateway" value="melat" checked="checked" />
                    <span class="checkbox"></span>
                    بانک ملت
                </label>
            </div>
            
            &nbsp;&nbsp;
            
            <div class="inline-block center-align">
                <label>
                    <img src="/images/gateways/meli.png" alt="بانک ملی" />
                    <br />
                    <input type="radio" name="payment_gateway" value="meli" />
                    <span class="checkbox"></span>
                    بانک ملی
                </label>
            </div>
            
            &nbsp;&nbsp;
            
            <div class="inline-block center-align">
                <label>
                    <img src="/images/gateways/parsian.png" alt="بانک پارسیان" />
                    <br />
                    <input type="radio" name="payment_gateway" value="parsian" />
                    <span class="checkbox"></span>
                    بانک پارسیان
                </label>
            </div>
            
            &nbsp;&nbsp;
            
            <div class="inline-block center-align">
                <label>
                    <img src="/images/gateways/saman.png" alt="بانک سامان" />
                    <br />
                    <input type="radio" name="payment_gateway" value="saman" />
                    <span class="checkbox"></span>
                    بانک سامان
                </label>
            </div>
            
            &nbsp;&nbsp;
            
            <div class="inline-block center-align">
                <label>
                    <img src="/images/gateways/zarinpal.png" alt="زرین پال" />
                    <br />
                    <input type="radio" name="payment_gateway" value="zarinpal" />
                    <span class="checkbox"></span>
                    زرین پال
                </label>
            </div>
            
            &nbsp;&nbsp;
            
            <div class="inline-block center-align">
                <label>
                    <img src="/images/gateways/jahanpay.png" alt="جهان پی" />
                    <br />
                    <input type="radio" name="payment_gateway" value="jahanpay" />
                    <span class="checkbox"></span>
                    جهان پی
                </label>
            </div>
            
            <br />
            <br />
            <button type="submit">
                <span class="sprite icn-transactions"></span>
                <?php echo $this->translate('Recharge Account'); ?>
            </button>
        </div>
    </div>
</form>

<?php

endif;
?>