<?php
/**
 * kPaste   -   kpaste.ir - kcoder.ir
 * 
 * @link        http://kcoder.ir/kpaste
 * @copyright   (c) 2013, kcoder.ir
 * @license     Proprietary
 * 
 * @filename    campaign-stats.phtml
 * @createdat   Jul 26, 2013 4:41:57 PM
 */


$title = $this->translate('Campaign Stats');
$this->headTitle($title);

if(isset($this->error) && $this->error):
?>
    <div class="error">
        <?php 
        switch($this->result):
            case 'ACCESS_DENIED':
                echo '<p>';
                echo $this->translate('Access denied! You don\'t have permission to access this area.');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
            case 'INVALID_CAMPAIGNID':
                echo '<p>';
                echo $this->translate('This campaign does not exist, or has been deleted.');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
            case 'CAMPAIGN_IS_NOT_YOURS':
                echo '<p>';
                echo $this->translate('This is not your campaign and you don\'t have permission to view its stats.');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
            default:
                echo '<p>';
                echo $this->translate('An unknown error has occured!');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
        endswitch;
        ?>
    </div>
<?php
endif;

if(isset($this->campaign) && isset($this->adsViews)):
?>
<h2>'<?php echo $this->campaign->campaign_title . '\' ' . $this->translate('Statistics'); ?></h2>
<br />
<div id='campaignGraph'></div>
<script>
    updateActiveCampaignGraph(<?php echo $this->campaign->campaignid; ?>, 'campaignGraph'); 
</script>
<br />

<table cellspacing="0" class='table' id='campaignStatsTable'>
    <thead>
        <tr>
            <th>#</th>
            <th><?php echo $this->translate('Country/IP'); ?></th>
            <th><?php echo $this->translate('IP Address'); ?></th>
            <th><?php echo $this->translate('Date'); ?></th>
        </tr>
    </thead>
    <tbody>
    <?php 
    $index = 0;
    foreach($this->adsViews as $adView): 
    $index++;
    ?>
    <tr>
        <td><?php echo $index; ?></td>
        <td>
            <img src='/images/country-flags/<?php echo $adView->countryShortName; ?>.png' />
            <?php echo $adView->countryLongName; ?>
        </td>
        <td><?php echo $adView->viewer_ip; ?></td>
        <td>
            <?php 
            echo \KpasteCore\KDateTime\KDateTime::PrefDate($adView->viewed_at); 
            ?>
        </td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php
endif;