<?php
/**
 * kPaste   -   kpaste.ir - kcoder.ir
 * 
 * @link        http://kcoder.ir/kpaste
 * @copyright   (c) 2013, kcoder.ir
 * @license     Proprietary
 * 
 * @filename    view-my-pastes.phtml
 * @createdat    Jul 16, 2013 7:28:58 PM
 */

$title = $this->translate('My Campaigns');
$this->headTitle($title);


if(isset($this->error) && $this->error):
?>
    <div class="error">
        <?php 
        switch($this->result):
            case 'ACCESS_DENIED':
                echo '<p>';
                echo $this->translate('You don\'t have permission to access this area. Please log in to continue!');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
            default:
                echo '<p>';
                echo $this->translate('An unknown error has occured!');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
        endswitch;
        ?>
    </div>
<?php
endif;

if(isset($this->myCampaigns)):
?>
<span id="campaignCMenuTranslations" class="hidden">
    <span><?php echo $this->translate('Go to URL'); ?></span>
    <span><?php echo $this->translate('Edit Compaign'); ?></span>
    <span><?php echo $this->translate('View/Upload Banner'); ?></span>
    <span><?php echo $this->translate('View Stats'); ?></span>
    <span><?php echo $this->translate('Extend Campaign'); ?></span>
    <span><?php echo $this->translate('Pause Campaign'); ?></span>
    <span><?php echo $this->translate('Resume Campaign'); ?></span>
</span>

<h3 class="center-align"><?php echo $this->translate('My Campaigns'); ?></h3>
<h5><?php echo $this->translate('You can right click on any of your campaigns to view a list of available options'); ?></h5>
<table cellspacing="0" border="0" class="table" id="myCampaignsTable">
    <thead>
        <tr>
            <th><?php echo $this->translate('Title'); ?></th>
            <th><?php echo $this->translate('Type'); ?></th>
            <th><?php echo $this->translate('Scope'); ?></th>
            <th><?php echo $this->translate('Total Credits'); ?></th>
            <th><?php echo $this->translate('Daily Credits'); ?></th>
            <th><?php echo $this->translate('Remaining Credits'); ?></th>
            <th><?php echo $this->translate('Status'); ?></th>
            <th><?php echo $this->translate('Start Date'); ?></th>
            <th><?php echo $this->translate('Extension Date'); ?></th>
            <th><?php echo $this->translate('Finish Date'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->myCampaigns as $myCampaign): ?>
        <tr class="campaignRow cursor-pointer" oncontextmenu="campaignContextMenu(
            event,
            <?php echo $myCampaign->campaignid; ?>,
            '<?php echo $myCampaign->campaign_url; ?>',
            '<?php echo $myCampaign->campaign_banner; ?>',
            '<?php echo $this->url('advertiser', array('lang' => substr($this->layout()->language, 0, 2))); ?>'
            );">
    
            <td><?php echo $myCampaign->campaign_title; ?></td>
            <td>
                <?php 
                switch( $myCampaign->campaign_type )
                {
                    case 'square_button_ltr'    : echo $this->translate('Left, Top or Right Square Button'); break;
                    case 'square_button_b'      : echo $this->translate('Bottom Square Button'); break;
                    case 'vertical_banner'      : echo $this->translate('Vertical Banner'); break;
                    case 'leaderboard_t'        : echo $this->translate('Top Leaderboard'); break;
                    case 'leaderboard_b'        : echo $this->translate('Bottom Leaderboard'); break;
                    case 'iframe'               : echo $this->translate('Inline Frame Ads'); break;
                }
                ?>
            </td>
            <td>
                <?php echo ($myCampaign->campaign_scope == 'local') ? $this->translate('Local') :
                            $this->translate('Global'); ?>
            </td>
            <td><?php echo $myCampaign->total_credits; ?></td>
            <td><?php echo $myCampaign->daily_credits; ?></td>
            <td><?php echo $myCampaign->remaining_credits; ?></td>
            <td>
                <?php
                switch($myCampaign->status)
                {
                    case 'pending':
                        echo $this->translate('Pending Approval');
                        break;
                    case 'active':
                        echo $this->translate('Active');
                        break;
                    case 'paused':
                        echo $this->translate('Paused By User');
                        break;
                    case 'rejected':
                        $msg = $this->translate('Your campaign has been rejected due to the following reason:<br />');
                        if($myCampaign->rejection_reason && strlen($myCampaign->rejection_reason))
                            $msg .= $myCampaign->rejection_reason;
                        else
                            $msg .= $this->translate('Unfortunately no reason has been specified!');
                        ?>
                        <a href="#" onclick="showMessageBox('<?php echo $msg;?>', 
                            '<?php echo $this->translate('OK'); ?>', 'msgbox'); return false;">
                        <?php
                        echo $this->translate('Rejected');
                        ?>
                        </a>
                        <?php
                        break;
                    case 'canceled':
                        echo $this->translate('Canceled');
                        break;
                    case 'finished':
                        echo $this->translate('Finished');
                        break;
                }
                ?>
            </td>
            <td>
                <?php 
                if($myCampaign->start_date)
                    echo KpasteCore\KDateTime\KDateTime::PrefDate($myCampaign->start_date); 
                else
                    echo $this->translate('Not Started Yet')
                ?>
            </td>
            <td>
                <?php 
                if($myCampaign->extension_date)
                    echo KpasteCore\KDateTime\KDateTime::PrefDate($myCampaign->extension_date); 
                else
                    echo $this->translate('Never');
                ?>
            </td>
            <td>
                <?php 
                if($myCampaign->finished_date)
                    echo KpasteCore\KDateTime\KDateTime::PrefDate($myCampaign->finished_date); 
                else
                    echo $this->translate('Not Finished Yet');
                ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<br />
<?php
echo $this->paginationControl(
    $this->myCampaigns,
    'sliding',
    array( 'partial/paginator.phtml', 'Admin' ),
    array( 
        'route'         => 'advertiser', 
        'action'        => 'Campaigns',
    )
);
?>
<script src="/js/contextmenu.js"></script>
<?php
endif;