<?php
/**
 * kPaste   -   kpaste.ir - kcoder.ir
 * 
 * @link        http://kcoder.ir/kpaste
 * @copyright   (c) 2013, kcoder.ir
 * @license     Proprietary
 * 
 * @filename    view-campaign.phtml
 * @createdat   Jul 15, 2013 4:41:57 PM
 */


$title = $this->translate('New Campaign');
$this->headTitle($title);

if(isset($this->error) && $this->error):
?>
    <div class="error">
        <?php 
        switch($this->result):
            case 'ACCESS_DENIED':
                echo '<p>';
                echo $this->translate('Access denied! You don\'t have permission to access this area.');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
            case 'NOT_ENOUGH_BALANCE':
                echo '<p>';
                echo sprintf($this->translate('Sorry! But your balance is not enough to create this
                    campaign. Your balance is %s%s. You need %s%s to create this campaign.'), 
                        $this->account_balance, $this->currency, $this->price, $this->currency);
                echo '<a href="' . $this->url('advertiser', array('lang' => substr($this->layout()->language, 0, 2),'action' => 'AccountBalance')) . '" target="_blank">';
                echo $this->translate('You need to recharge first and then try again.') . '</a>';
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
            case 'INVALID_DATA_PROVIDED':
                echo '<p>';
                echo $this->translate('You provided invalid data in the form!');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
            default:
                echo '<p>';
                echo $this->translate('An unknown error has occured!');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
        endswitch;
        ?>
    </div>
<?php
endif;

if(isset($this->error) && $this->error && $this->result == 'ACCESS_DENIED'):
?>
<div class="center-align">
    <a class="big-button" href="<?php echo $this->url('user', array('lang' => substr($this->layout()->language, 0, 2),'action' => 'signup')); ?>?advertiser=true">
        <?php echo $this->translate('Register and Start Your Campaigns'); ?>
    </a>
</div>
<?php
endif;

if(isset($this->error) && $this->error == false):
?>
    <div class="notification">
        <p>
            <?php echo $this->translate('Campaign created successfully and it\'s awaiting approval from our staff.'); ?>
            <br />
            <?php echo $this->translate('Final Price'); ?>: <?php echo $this->price . $this->currency; ?>
            <?php if($this->discount): ?>
                <br />
                <?php echo sprintf($this->translate('Your coupon granted you %s%% discount.'), 
                        $this->discount); ?>
                <br />
                <?php echo $this->translate('Price Without Coupon'); ?>:
                <?php echo $this->originalPrice . $this->currency; ?>
            <?php endif; ?>
            <?php if(isset($this->campaignid)): ?>
                <br />
                <a href="<?php echo $this->url('advertiser', 
                array('lang'  => substr($this->layout()->language, 0, 2),'action' => 'UploadBanner', 'param1' => $this->campaignid)); ?>">
                    <?php echo $this->translate('Upload a banner for this campaign'); ?>
                </a>
            <?php endif; ?>
        </p>
    </div>
<?php
endif;

if(isset($this->form)):
    $form = $this->form;

    if(!$this->campaignid)
    {
        $form->setAttribute('action', $this->url('advertiser', array('lang' => substr($this->layout()->language, 0, 2),'action' => 'NewCampaign')));;
    }
    else
    {
        $form->setAttribute('action', $this->url('advertiser', array('lang' => substr($this->layout()->language, 0, 2),'action' => 'NewCampaign', 'param1' => $this->campaignid)));    
    }
    
    $form->prepare();
    
    $helpText = '<ol>';
    $helpText.= '<li>' . $this->translate('Left, Top or Right Square Button') . '</li>';
    $helpText.= '<li>' . $this->translate('Bottom Square Button') . '</li>';
    $helpText.= '<li>' . $this->translate('Vertical Banner') . '</li>';
    $helpText.= '<li>' . $this->translate('Top Leaderboard') . '</li>';
    $helpText.= '<li>' . $this->translate('Bottom Leaderboard') . '</li>';
    $helpText.= '</ol><br /><br />';
    $helpText.= '<div class=\\\'center-align\\\'><img src=\\\'/images/ads_legend.png\\\' width=\\\'608\\\' height=\\\'450\\\' alt=\\\'ads\\\' /></div>';
    
?>
    <div class="width60">
        <h3><?php echo $this->translate('Create New Campaign'); ?></h3>
        <p><?php echo $this->translate('Please note that:'); ?></p>
        <ul>
            <li><?php echo $this->translate('You should fill out all of the fields. You can edit your campaign later, as long as it\'s pending.'); ?></li>
            <li><?php echo sprintf($this->translate('A local scope makes your ads only available to IP Addresses with "%s" country code.'), $this->locale); ?></li>
            <li><?php echo sprintf($this->translate('If this is your first time, check out the %s section before choosing a campaign type.'), 
                    '<a href="#" onclick="showMessageBox(\'' . $helpText . '\', \'msgbox\'); return false;">' . $this->translate('help') . '</a>'); ?></li>
            <li><?php echo $this->translate('Campaign Credits is the total number of times your ads will be displayed to unique visitors'); ?></li>
            <li>
                <?php echo $this->translate('Correct URL examples are:'); ?>
                <ul>
                    <li>http://kpaste.ir</li>
                    <li>http://kcoder.ir/products/kpaste</li>
                    <li>http://blog.kcoder.ir</li>
                </ul>
            </li>
            <li>
                <span class="bold">
                <?php echo sprintf($this->translate('You can always order your banner at <a href="http://kcoder.ir"' .
                        ' title="%s" target="_blank">%s</a> and pay online for it.'), $this->translate('kCoder'),
                        $this->translate('kCoder')); ?>
                </span>
            </li>
            <?php if($this->iframeEnabled): ?>
            <li class="bold"><?php echo $this->translate('Inline Frame Ads ACTUALLY increase the number of visitors of your website!'); ?></li>
            <?php endif; ?>
        </ul>
<?php
    echo $this->form()->openTag($form);
?>
    <div class="formRow">
        <label>
            <span><?php echo $this->translate('Campaign Title'); ?>:</span>
            <?php echo $this->formRow($form->get('campaign_title')); ?>
        </label>
    </div>

    <div class="formRow">
        <label>
            <span><?php echo $this->translate('Campaign Scope'); ?>:</span>
            <?php 
            $form->get('campaign_scope')->setValueOptions(array(
                'global'    => $this->translate('Global'),
                'local'     => $this->translate('Local') . '(' . $this->locale . ')',
            ))->setAttribute('id', 'campaignScope');
            echo $this->formRow($form->get('campaign_scope')); 
            ?>
        </label>
    </div>
    
    <div class="formRow">
        <label>
            <span><?php echo $this->translate('Campaign Type'); ?>:</span>
            <?php 
            echo $this->formRow($form->get('campaign_type')); 
            ?>
        </label>
    </div>

    <div class="formRow">
        <label>
            <span><?php echo $this->translate('Campaign Credits'); ?>:</span>
            <?php 
            $form->get('total_credits')->setAttribute('id', 'campaignCredits');
            echo $this->formRow($form->get('total_credits'));
            ?>
        </label>
    </div>

    <div class="formRow">
        <label>
            <span><?php echo $this->translate('Daily Credits Limit'); ?>:</span>
            <?php echo $this->formRow($form->get('daily_credits')); ?>
        </label>
    </div>

    <div class="formRow">
        <label>
            <span><?php echo $this->translate('Campaign URL'); ?>:</span>
            <?php echo $this->formRow($form->get('campaign_url')); ?>
        </label>
    </div>
        
    <div class="formRow">
        <label>
            <span><?php echo $this->translate('Discount Coupon'); ?>:</span>
            <input type='text' name='couponid' id='couponid' 
                   onkeyup='updateCoupon("<?php echo substr($this->layout()->language, 0, 2); ?>");'
                   onchange='updateCoupon("<?php echo substr($this->layout()->language, 0, 2); ?>");' />
        </label>
    </div>

    <table class="table">
        <tr>
            <td><?php echo $this->translate('Total Price'); ?></td> 
            <td>
                <?php echo $this->currency; ?>
                <span id='totalPrice'>0</span>
            </td>
        </tr>
        <tr>
            <td><?php echo $this->translate('Total Price With Discount(Without Coupon)'); ?>&nbsp;&nbsp;&nbsp;</td>
            <td>
                <?php echo $this->currency; ?>
                <span id='totalPriceDiscounted'>0</span>
            </td>
        </tr>
        <tr>
            <td><?php echo $this->translate('Unit Price'); ?></td>
            <td>
                <?php echo $this->currency; ?>
                <span id='unitPrice'>0</span>
            </td>
        </tr>
        <tr>
            <td><?php echo $this->translate('Provided Coupon Discount'); ?></td>
            <td>
                <span id='couponDiscount'><?php echo $this->translate('No Coupon Selected'); ?></span>
            </td>
        </tr>
        <tr>
            <td><?php echo $this->translate('Your Account Balance'); ?></td>
            <td>
                <?php echo $this->currency; ?>
                <span><?php echo (int)$this->account_balance; ?></span>
            </td>
        </tr>
    </table>
    <br />
    <input type='hidden' id='localPriceFactor' value='<?php echo $this->localPriceFactor; ?>' />
    <input type='hidden' id='square_button_ltr_price' value='<?php echo $this->price_sqbtnlrt; ?>' />
    <input type='hidden' id='square_button_b_price' value='<?php echo $this->price_sqbtnb; ?>' />
    <input type='hidden' id='vertical_banner_price' value='<?php echo $this->price_verbnr; ?>' />
    <input type='hidden' id='leaderboard_t_price' value='<?php echo $this->price_leaderboardt; ?>' />
    <input type='hidden' id='leaderboard_b_price' value='<?php echo $this->price_leaderboardb; ?>' />
    <input type='hidden' id='iframe_price' value='<?php echo $this->price_iframe; ?>' />
    <input type='hidden' id='discountFactor' value='<?php echo $this->discountFactor; ?>' />
    <?php echo $this->formRow($form->get('csrf')); ?>
    
    <?php 
    $form->get('submit')->setAttribute('value', $this->translate('Create Campaign'));
    echo $this->formRow($form->get('submit')); 
    ?>

<?php
    echo $this->form()->closeTag();
?>
    </div>
<?php
endif;
?>

<script src="/js/campaign.js"></script>
<script>
    updatePrices();
</script>