<?php
/**
 * kPaste   -   kpaste.ir - kcoder.ir
 * 
 * @link        http://kcoder.ir/kpaste
 * @copyright   (c) 2013, kcoder.ir
 * @license     Proprietary
 * 
 * @filename    new-paste.php
 * @createdat   Jul 15, 2013 4:41:57 PM
 */

$title = $this->translate('Confirm Action');
$this->headTitle($title);

if(isset($this->error) && $this->error):
?>
    <div class="error">
        <?php 
        switch($this->result):
            case 'INVALID_CAMPAIGNID':
                echo '<p>';
                echo $this->translate('Either the campaign you are refering to doesn\'t ' .  
                    'exist or campaign ID has not been provided.');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
            case 'CAMPAIGN_IS_NOT_YOURS':
                echo '<p>';
                echo $this->translate( 'You don\'t have permission to access this campaign!' );
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
            case 'CAMPAIGN_NOT_ACTIVE':
                echo '<p>';
                echo $this->translate( 'This is not an active campaign. You can\'t pause it!' );
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
            default:
                echo '<p>';
                echo $this->translate( 'An unknown error has occured!' );
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
        endswitch;
        ?>
    </div>
<?php
endif;


if(isset($this->campaignTitle)):
?>
<h2><?php echo sprintf($this->translate('Do you really want to pause \'%s\'?'), $this->campaignTitle); ?></h2>
<form action='<?php echo $this->url('advertiser', array(
                        'lang'      => substr($this->layout()->language, 0, 2),
                        'action'    => 'PauseCampaign',
                        'param1'    => $this->campaignid,
                    )); ?>' method='post'>
    <button type='submit' name='confirm' value='YES'><?php echo $this->translate('Yes'); ?></button>
    <button type='submit' name='confirm' value='NO'><?php echo $this->translate('No'); ?></button>
</form>
<?php
endif;