<?php
/**
 * kPaste   -   kpaste.ir - kcoder.ir
 * 
 * @link        http://kcoder.ir/kpaste
 * @copyright   (c) 2013, kcoder.ir
 * @license     Proprietary
 * 
 * @filename    create-new-admin.phtml
 * @createdat   Jul 26, 2013 4:41:57 PM
 */


$title = $this->translate('Create New Admin');
$this->headTitle($title);

if(isset($this->error) && $this->error):
?>
    <div class="error">
        <?php 
        switch($this->result):
            case 'ACCESS_DENIED':
                echo '<p>';
                echo $this->translate('Access denied! You don\'t have permission to access this area.');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
            case 'USER_NAME_ALREADY_EXISTS':
                echo '<p>';
                echo $this->translate('This username already exists!');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
            case 'EMAIL_ALREADY_EXISTS':
                echo '<p>';
                echo $this->translate('This email already exists!');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
            case 'INVALID_DATA_PROVIDED':
                echo '<p>';
                echo $this->translate('The data you have entered in the form is not valid!');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
            default:
                echo '<p>';
                echo $this->translate('An unknown error has occured!');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
        endswitch;
        ?>
    </div>
<?php
endif;

if( isset( $this->error ) && !$this->error ):
?>
<div class="notification">
    <p>
        <?php echo $this->translate( 'Admin account was created successfully. Now the user needs to activate the account by verifying his email address.' ); ?>
    </p>
</div>
<?php
endif;

if( isset( $this->newAdminForm ) ):
    $form = $this->newAdminForm;
    $form->setAttribute( 'action', $this->url( 'admin', array(
        'lang'          => substr($this->layout()->language, 0, 2),
        'controller'    => 'MasterAdmin',
        'action'        => 'CreateNewAdmin',
    ) ) );
    $form->prepare();
    echo $this->form()->openTag( $form );
?>
    <div class="width60">
        <div class="formRow">
            <label>
                <span><?php echo $this->translate('Username'); ?>:</span>
                <?php echo $this->formRow($form->get('username')); ?>
            </label>
        </div>

        <div class="formRow">
            <label>
                <span><?php echo $this->translate('Email'); ?>:</span>
                <?php echo $this->formRow($form->get('email')); ?>
            </label>
        </div>

        <div class="formRow">
            <label>
                <span><?php echo $this->translate('Password'); ?>:</span>
                <?php echo $this->formRow($form->get('password')); ?>
            </label>
        </div>

        <div class="formRow">
            <label>
                <span><?php echo $this->translate('Repeat password'); ?>:</span>
                <?php echo $this->formRow($form->get('repassword')); ?>
            </label>
        </div>

        <div class="formRow">
            <label>
                <span><?php echo $this->translate('First Name'); ?>:</span>
                <?php echo $this->formRow($form->get('firstname')); ?>
            </label>
        </div>  

        <div class="formRow">
            <label>
                <span><?php echo $this->translate('Last Name'); ?>:</span>
                <?php echo $this->formRow($form->get('lastname')); ?>
            </label>
        </div> 

        <div class="formRow">
            <label>
                <span><?php echo $this->translate('Cell phone number'); ?>:</span>
                <?php echo $this->formRow($form->get('cell_number')); ?>
            </label>
        </div> 

        <div class="formRow">
            <label title="<?php echo $this->translate('Security Question (for password reset)'); ?>">
                <span><?php echo $this->translate('Security Question (for password reset)'); ?>:</span>
                <?php echo $this->formRow($form->get('security_question')); ?>
            </label>
        </div> 

        <div class="formRow">
            <label title="<?php echo $this->translate('Security Question Answer'); ?>">
                <span><?php echo $this->translate('Security Question Answer'); ?>:</span>
                <?php echo $this->formRow($form->get('security_question_answer')); ?>
            </label>
        </div> 

        <?php echo $this->formRow($form->get('csrf')); ?>

        <?php 
        $form->get( 'submit' )->setAttribute( 'value', $this->translate( 'Create Admin' ) );
        echo $this->formRow( $form->get( 'submit' ) ); 
        ?>

    </div>
<?php
endif;