<?php
/**
 * kPaste   -   kpaste.ir - kcoder.ir
 * 
 * @link        http://kcoder.ir/kpaste
 * @copyright   (c) 2013, kcoder.ir
 * @license     Proprietary
 * 
 * @filename    change-status.phtml
 * @createdat   aug 2, 2013 4:41:57 PM
 */


$title = $this->translate('Change Status');
$this->headTitle($title);

if(isset($this->error) && $this->error ):
?>
    <div class="error">
        <?php 
        switch($this->result):
            case 'ACCESS_DENIED':
                echo '<p>';
                echo $this->translate('Access denied! You don\'t have permission to access this area.');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
            case 'INVALID_USER_ID':
                echo '<p>';
                echo $this->translate('Invalid user ID has been provided!');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
            default:
                echo '<p>';
                echo $this->translate('An unknown error has occured!');
                echo '</p>';
                echo '<footer class="error-code">' . $this->result . '</footer>';
                break;
        endswitch;
        ?>
    </div>
<?php
endif;

if( isset( $this->userid ) )
    $continue = $this->url( 'admin', array(
        'lang'          => substr($this->layout()->language, 0, 2),
        'controller'    => 'UserManagement',
        'action'        => 'ViewUsers',
        'param1'        => $this->userid
    ) );
else
    $continue = $this->url( 'admin', array(
        'lang'          => substr($this->layout()->language, 0, 2),
        'controller'    => 'UserManagement',
        'action'        => 'ViewUsers',
    ) );

?>
<a href='<?php echo $continue; ?>'><?php echo $this->translate( 'Continue' ); ?></a>